# -*- coding: utf-8 -*-
"""WEEK II

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ChpNWm09e72hsHEgxsF_vg4dZU5Wq3DC

SECTION A

1)Create a function that takes three integer arguments (a, b, c) and returns the amount of integers which are of equal value.
"""

def sum(x, y, z):
  if x == y or y == z or z == x:
    sum = 3
  else:
    sum = 0
  return sum
print(sum(5, 5, 5))
print(sum(3, 4, 1))

"""2)Write a function that converts a dictionary into a list of keys-values tuples."""

def DtoLoT(dict):
    dict = {'om':33, 'ajay':63, 'chetan':25, 'vedant':45}
    list = [(k, v) for k, v in dict.items()]

    list.sort(key = lambda x: x[0])
    return list

print(DtoLoT(dict))

"""3)Write a function that creates a dictionary with each (key, value) pair being the (lower case, upper case) versions of a letter, respectively."""

def function2(list):
 list = ["a", "b", "c", "d"]
 b = dict((i, i.upper()) for i in list)
 return b
    
print(function2(list))

"""4)Write a function, that replaces all vowels in a string with a specified vowel."""

def replaceVowels(str, K):
    vowels = 'aeiou'
    for i in vowels:
        str = str.replace(i, K)
    return str
input_str = "Python is computer language"
K = "e"
print("Input string =", input_str)
print("Specified vowel =", K)
print("After replacing =", replaceVowels(input_str, K))

"""5)Create a function that takes a string as input and capitalizes a letter if its ASCII code is even and returns its lower case version if its ASCII code is odd."""

def Python(sy):
  ab = []
  for index, c in enumerate(sy):
    if index % 2 == 0:
      ab.append(c.upper())
    else:
      ab.append(c.lower())
  return '' .join(ab)
print(Python("Python is computer language:"))

"""SECTION B"""

def fact(n):
  fact=1
  for i in range(1,n+1):
    fact=fact*i
  print(fact)  
fact(5)

def rotate(a,d):
    n=len(a)
    a[:]=a[d:n]+a[0:d]
    return a
a = [3,4,5,6,8,9,1]
print("Rotated list is")
print(rotate(a,1))

colors={}
def insert(a):
  if a in colors:
    colors[a]+=1
  else:
    colors[a]=1  
insert('Red')
insert('green')
insert('Blue')
insert('White')
insert('Red')
print(len(colors))

def sumlist(list):
    sum=0
    for i in range(len(list)):
        sum = sum+list[i]
    return sum
list = [20,40,60]
print(list)
print("sum of list: ",sumlist(list))

def mul_list(list) :         
    product = 1
    for i in list:
         product = product * i
    return product     
list1 = [5,6,7,8]
print(list1)
print("product: ") 
print(mul_list(list1))